### ISSUE TITLE
Error in ResultMerge.py

### ISSUE THREAD

**Issue by Smoothing97** [CAPTAIN-WHU/DOTA_devkit#16]
按照readme走流程，特意用了example的几张图片，分割处理数据然后valid，得到了15个results文件，大概如下：
P1234__1__0___2976 0.011820 696.137329 983.967957 756.505493 1024.000000
P1234__1__0___2976 0.010101 1.000000 924.940125 19.290693 969.360168
P1234__1__0___2976 0.008857 795.971069 960.030212 853.479736 1024.000000
P1234__1__0___2976 0.008307 1.000000 979.919922 124.899353 1024.000000
P1234__1__0___2976 0.010262 560.123779 828.110779 578.821289 863.667175
P1234__1__0___2976 0.010617 538.470886 988.313965 599.414612 1024.000000
P1234__1__0___2976 0.010275 764.724182 968.561584 819.250671 1024.000000
P1234__1__0___2976 0.009946 1004.529358 704.344116 1024.000000 733.913330

放到resultmerge.py，src_path=15个results的存放路径，dct_path=新建存放路径，总报错：
(mytensorflow) aa@aa-GPU:~/DOTA_YOLOv2/DOTA_devkit$ python ResultMerge.py
Traceback (most recent call last):
  File "ResultMerge.py", line 161, in <module>
    mergebypoly(r'path_to_configure', r'path_to_configure')
  File "ResultMerge.py", line 158, in mergebypoly
    py_cpu_nms_poly)
  File "ResultMerge.py", line 127, in mergebase
    nameboxnmsdict = nmsbynamedict(nameboxdict, nms, nms_thresh)
  File "ResultMerge.py", line 76, in nmsbynamedict
    keep = nms(np.array(nameboxdict[imgname]), thresh)
  File "ResultMerge.py", line 12, in py_cpu_nms_poly
    scores = dets[:, 8]
IndexError: index 8 is out of bounds for axis 1 with size 5

**Comment by dingjiansw101** [comment]
因为你的结果是Task2的，所以你应该使用mergebyrec()而不是mergebypoly

**Comment by Smoothing97** [comment]
谢谢您的指点，跑出结果了，但是用dota_evaluation_task2.py测map结果不太好：
...
classname: helicopter
check fp: [ 1.  1.  1. ...,  1.  1.  1.]
check tp [ 0.  0.  0. ...,  0.  0.  0.]
npos num: 0
ap:  0.0
map: 9.21994456949e-06
classaps:  [ 0.00310588  0.00575313  0.          0.          0.          0.00032483
  0.00137685  0.00151971  0.          0.00174951  0.          0.          0.
  0.          0.        ]
困惑，我是按照教程摸索来的，但是不知道哪里出了问题

**Comment by dingjiansw101** [comment]
你是用的我们提供的模型跑的结果，还是自己训练的？

**Comment by Yanhong-Li** [comment]
我想问一下怎么获取15个results？
