### ISSUE TITLE
win10 下return importlib.import_module('_polyiou')

### ISSUE THREAD

**Issue by baronzyy** [CAPTAIN-WHU/DOTA_devkit#52]
Traceback (most recent call last):
  File "datasets/DOTA_devkit\polyiou.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\ProgramData\Miniconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/CFC-Net-master/train.py", line 16, in <module>
    from eval import evaluate
  File "E:\CFC-Net-master\eval.py", line 21, in <module>
    from datasets.DOTA_devkit.ResultMerge_multi_process import ResultMerge
  File "E:\CFC-Net-master\datasets\DOTA_devkit\ResultMerge_multi_process.py", line 18, in <module>
    import polyiou
  File "datasets/DOTA_devkit\polyiou.py", line 17, in <module>
    _polyiou = swig_import_helper()
  File "datasets/DOTA_devkit\polyiou.py", line 16, in swig_import_helper
    return importlib.import_module('_polyiou')
  File "C:\ProgramData\Miniconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: 找不到指定的模块。

请问有没有遇到过这种情况

**Comment by xiaoyihit** [comment]
Have u solved this problem? Simmilar problem encountered here.
in DOTA_devkit/polyiou.py:
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_polyiou')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_polyiou')

    File "/remote-home/xiaoyi/AerialDetection/mmdet/core/bbox/geometry.py", line 5, in <module>
    import DOTA_devkit.polyiou as polyiou
  File "/remote-home/xiaoyi/AerialDetection/DOTA_devkit/polyiou.py", line 19, in <module>
    _polyiou = swig_import_helper()
  File "/remote-home/xiaoyi/AerialDetection/DOTA_devkit/polyiou.py", line 17, in swig_import_helper
    return importlib.import_module('_polyiou')
  File "/opt/conda/envs/AerialDetection/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_polyiou'

But I do have _polyiou.cpython-36m-x86_64-linux-gnu.so in the same dir ./DOTAdevkit, and this code does not involve deprecated imp, so I wonder why.
